apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop
  labels:
    name: sock-shop
---
apiVersion: v1
kind: Namespace
metadata:
  name: other-namespace
  labels:
    name: other-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sock-shop
  name: sock-shop-admin
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: sock-shop
  name: admin-group
subjects:
  - kind: Group
    name: admin-group
    namespace: sock-shop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sock-shop-admin
