on: pull_request

name: Check

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@fcd8bb1e0a3c9d2a0687615ee31d34d8aea18a96
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl

      - run: aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}

      - run: ./kubectl apply -f ./manifests/namespace.yml

      - run: ./kubectl diff -f ./manifests/sock-shop.yml 2>&1 | tee diff.log

      - run: |
          details="$(cat diff.log)"
          details="${details//'%'/'%25'}"
          details="${details//$'\n'/'%0A'}"
          details="${details//$'\r'/'%0D'}"
          echo "::set-output name=details::$details"

      - uses: actions/github-script@v5
        with:
          script: |
            const { OUTPUT_VALIDATE } = process.env
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### kubectl diff result\n\n<details>\n\n\`\`\`${DETAILS}\n\`\`\`\n\n</details>`
            })
        env:
          DETAILS: "${{ steps.run_validate.outputs.details }}"
