on: workflow_dispatch

name: Release

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@fcd8bb1e0a3c9d2a0687615ee31d34d8aea18a96
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl

      - run: aws eks update-kubeconfig --name "$CLUSTER_NAME"
        env:
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

      - run: ./kubectl apply -f ./manifests/namespace.yml

      - run: ./kubectl diff -f ./manifests/sock-shop.yml
